<?php
// helpers/ui_strings.php

return [
    'pl' => [
        'index' => [
            'title' => 'IDML Translator Premium',
            'welcome' => 'Witaj, ',
            'logout' => 'Wyloguj',
            'upload_title' => 'Prześlij plik IDML',
            'upload_hint' => 'Przeciągnij i upuść lub kliknij, aby wybrać plik .idml',
            'target_lang' => 'Język docelowy',
            'submit' => 'Rozpocznij tłumaczenie',
        ],
        'login' => [
            'title' => 'Logowanie',
            'welcome_back' => 'Witaj ponownie',
            'username' => 'UŻYTKOWNIK',
            'password' => 'HASŁO',
            'submit' => 'Zaloguj do systemu',
            'error' => 'Błędny login lub hasło.',
        ],
        'translate' => [
            'title' => 'Panel Tłumaczenia',
            'processing' => 'Przetwarzanie...',
            'download' => 'Pobierz gotowy plik',
            'auto_translate' => 'Tłumacz automatycznie',
        ],
        'homepage' => [
            'hero_title' => 'Tłumacz IDML i Office nowej generacji',
            'hero_subtitle' => 'Zasilany przez AI. Precyzyjny. Błyskawiczny. Zachowuje układ Twoich dokumentów.',
            'cta_start' => 'Zacznij teraz',
            'cta_demo' => 'Wypróbuj demo',
            'login' => 'Zaloguj się',
            'register' => 'Zarejestruj się',
            'features_title' => 'Dlaczego my?',
            'feat_idml' => 'Perfekcyjne IDML',
            'feat_idml_desc' => 'Zachowujemy wszystkie style, warstwy i linki w Twoich plikach InDesign.',
            'feat_office' => 'Wsparcie Word i PPTX',
            'feat_office_desc' => 'Błyskawiczne tłumaczenie dokumentów Word i prezentacji PowerPoint.',
            'feat_ai' => 'Precyzyjny silnik OpenAI',
            'feat_ai_desc' => 'Wykorzystujemy najnowsze modele AI do kontekstowego tłumaczenia branżowego.',
        ],
        'register' => [
            'title' => 'Stwórz konto',
            'submit' => 'Zarejestruj',
            'success' => 'Konto stworzone! Możesz się zalogować.',
            'error' => 'Użytkownik już istnieje lub błąd danych.',
        ],
        'pricing' => [
            'title' => 'Wybierz plan dla swojego biznesu',
            'starter_name' => 'Starter',
            'starter_price' => '0 zł',
            'starter_feat' => ['3 projekty / msc', 'Podstawowe AI', 'Historia 7 dni'],
            'pro_name' => 'Professional',
            'pro_price' => '199 zł',
            'pro_feat' => ['Nielimitowane IDML', 'Wsparcie Office', 'Priorytetowe AI (GPT-4o)', 'Pełna Historia'],
            'enterprise_name' => 'Agency',
            'enterprise_price' => 'Wycena',
            'enterprise_feat' => ['Dostęp przez API', 'Dedykowany model AI', 'Wsparcie 24/7'],
            'cta' => 'Wybierz plan'
        ]
    ],
    'en' => [
        'index' => [
            'title' => 'Premium IDML Translator',
            'welcome' => 'Welcome, ',
            'logout' => 'Logout',
            'upload_title' => 'Upload IDML file',
            'upload_hint' => 'Drag and drop or click to select a .idml file',
            'target_lang' => 'Target Language',
            'submit' => 'Start Translation',
        ],
        'login' => [
            'title' => 'Login',
            'welcome_back' => 'Welcome Back',
            'username' => 'USERNAME',
            'password' => 'PASSWORD',
            'submit' => 'Login to system',
            'error' => 'Invalid username or password.',
        ],
        'translate' => [
            'title' => 'Translation Panel',
            'processing' => 'Processing...',
            'download' => 'Download finished file',
            'auto_translate' => 'Auto translate',
        ],
        'homepage' => [
            'hero_title' => 'Next-Gen IDML & Office Translator',
            'hero_subtitle' => 'Powered by AI. Precise. Instant. Preserves your document layouts.',
            'cta_start' => 'Get Started',
            'cta_demo' => 'Try Demo',
            'login' => 'Sign In',
            'register' => 'Sign Up',
            'features_title' => 'Why choose us?',
            'feat_idml' => 'Perfect IDML',
            'feat_idml_desc' => 'We preserve all styles, layers and links in your InDesign files.',
            'feat_office' => 'Word & PPTX Support',
            'feat_office_desc' => 'Instant translation of Word documents and PowerPoint presentations.',
            'feat_ai' => 'High-Precision OpenAI Engine',
            'feat_ai_desc' => 'We use the latest AI models for contextual industry translations.',
        ],
        'register' => [
            'title' => 'Create Account',
            'submit' => 'Register',
            'success' => 'Account created! You can now log in.',
            'error' => 'User already exists or data error.',
        ],
        'pricing' => [
            'title' => 'Plans for every business size',
            'starter_name' => 'Starter',
            'starter_price' => '$0',
            'starter_feat' => ['3 projects / mo', 'Basic AI engine', '7-day history'],
            'pro_name' => 'Professional',
            'pro_price' => '$49',
            'pro_feat' => ['Unlimited IDML', 'Office Support', 'Priority GPT-4o', 'Full History'],
            'enterprise_name' => 'Agency',
            'enterprise_price' => 'Custom',
            'enterprise_feat' => ['API Access', 'Custom AI fine-tuning', '24/7 Support'],
            'cta' => 'Choose plan'
        ]
    ],
    'de' => [
        'index' => [
            'title' => 'Premium IDML Übersetzer',
            'welcome' => 'Willkommen, ',
            'logout' => 'Abmelden',
            'upload_title' => 'IDML-Datei hochladen',
            'upload_hint' => 'Ziehen und ablegen oder klicken, um eine .idml Datei auszuwählen',
            'target_lang' => 'Zielsprache',
            'submit' => 'Übersetzung starten',
        ],
        'login' => [
            'title' => 'Anmeldung',
            'welcome_back' => 'Willkommen zurück',
            'username' => 'BENUTZERNAME',
            'password' => 'PASSWORT',
            'submit' => 'Im System anmelden',
            'error' => 'Ungültiger Benutzername oder Passwort.',
        ],
        'homepage' => [
            'hero_title' => 'IDML & Office Übersetzer der nächsten Generation',
            'hero_subtitle' => 'Unterstützt durch KI. Präzise. Sofort. Behält Ihre Dokumentlayouts bei.',
            'cta_start' => 'Jetzt starten',
            'cta_demo' => 'Demo ausprobieren',
            'login' => 'Anmelden',
            'register' => 'Registrieren',
            'features_title' => 'Warum wir?',
            'feat_idml' => 'Perfektes IDML',
            'feat_idml_desc' => 'Wir bewahren alle Stile, Ebenen und Verknüpfungen in Ihren InDesign-Dateien.',
            'feat_office' => 'Word & PPTX Unterstützung',
            'feat_office_desc' => 'Sofortige Übersetzung von Word-Dokumenten und PowerPoint-Präsentationen.',
            'feat_ai' => 'Hochpräzise OpenAI-Engine',
            'feat_ai_desc' => 'Wir nutzen die neuesten KI-Modelle für kontextbezogene Branchenübersetzungen.',
        ],
        'register' => [
            'title' => 'Konto erstellen',
            'submit' => 'Registrieren',
            'success' => 'Konto erstellt! Sie können sich jetzt anmelden.',
            'error' => 'Benutzer existiert bereits oder Datenfehler.',
        ],
        'pricing' => [
            'title' => 'Tarife für jede Unternehmensgröße',
            'starter_name' => 'Starter',
            'starter_price' => '0 €',
            'starter_feat' => ['3 Projekte / Monat', 'Basis-KI', '7 Tage Verlauf'],
            'pro_name' => 'Professional',
            'pro_price' => '49 €',
            'pro_feat' => ['Unbegrenzt IDML', 'Office-Support', 'Prioritäts-KI (GPT-4o)', 'Vollständiger Verlauf'],
            'enterprise_name' => 'Agentur',
            'enterprise_price' => 'Anfrage',
            'enterprise_feat' => ['API-Zugriff', 'Eigene KI-Modelle', '24/7 Support'],
            'cta' => 'Plan wählen'
        ]
    ]
];
